#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

module purge
module load intel/2017.4.196 parallel/mpi.intel.broadwell/2017.4.196 compilers/intel/2017.4.196

wmake libso ./solverBC
wmake ./solver
